[project]
name = "johns-piano-ai"
version = "0.1.0"
description = "Automatic piano transcription project"
authors = [{ name = "John Whalen" }]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py39']

[tool.pytest.ini_options]
addopts = "--ignore=data --maxfail=3"
testpaths = ["src/tests"]

[tool.mypy]
strict = true

[tool.setuptools]
packages = ["src"]

