# new version of the model since my first onces were doodoo. This one was also generated by Claude
import torch
import torch.nn as nn
import torch.nn.functional as F

# trains significantly slower than the other models as claude gave it to me. 
# took 21 minutes for one epoch on 1/6 of the dataset (245 forward passes).
# I suspect it was the BatchNorm2d layers combined with the large batch size (64)
class APT1(nn.Module):
    """
    Piano transcription model that predicts note activations, onsets, and velocities
    from audio spectrograms.
    
    Input shape: (batch_size, freq_channels, time_frames) = (64, 88, 157)
    Output shapes: 3 tensors of shape (64, 88, 157) for activations, onsets, velocities
    """
    
    def __init__(self, freq_bins=88, hidden_dim=256, num_layers=3):
        super(APT1, self).__init__()
        
        self.freq_bins = freq_bins
        self.hidden_dim = hidden_dim
        
        # Convolutional layers for feature extraction
        self.conv1 = nn.Conv2d(1, 32, kernel_size=(3, 3), padding=(1, 1))
        self.bn1 = nn.BatchNorm2d(32)
        
        self.conv2 = nn.Conv2d(32, 64, kernel_size=(3, 3), padding=(1, 1))
        self.bn2 = nn.BatchNorm2d(64)
        
        self.conv3 = nn.Conv2d(64, 128, kernel_size=(3, 3), padding=(1, 1))
        self.bn3 = nn.BatchNorm2d(128)
        
        # Bidirectional LSTM for temporal modeling
        self.lstm = nn.LSTM(
            input_size=128 * freq_bins,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=0.3 if num_layers > 1 else 0
        )
        
        # Fully connected layer to project LSTM output
        self.fc_shared = nn.Linear(hidden_dim * 2, 512)
        self.dropout = nn.Dropout(0.3)
        
        # Separate output heads for each task
        self.fc_activations = nn.Linear(512, freq_bins)
        self.fc_onsets = nn.Linear(512, freq_bins)
        self.fc_velocity = nn.Linear(512, freq_bins)

    def forward(self, x):
        """
        Forward pass of the model.
        
        Args:
            x: Input tensor of shape (batch_size, freq_bins, time_frames)
               e.g., (64, 88, 157)
        
        Returns:
            activations: Tensor of shape (batch_size, freq_bins, time_frames)
            onsets: Tensor of shape (batch_size, freq_bins, time_frames)
            velocity: Tensor of shape (batch_size, freq_bins, time_frames)
        """
        batch_size, freq_bins, time_frames = x.shape
        
        # Add channel dimension for conv layers: (B, 1, F, T)
        x = x.unsqueeze(1)
        
        # Convolutional feature extraction
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))
        
        # Reshape for LSTM: (B, T, C*F)
        # x shape: (B, 128, F, T)
        x = x.permute(0, 3, 1, 2)  # (B, T, 128, F)
        x = x.reshape(batch_size, time_frames, -1)  # (B, T, 128*F)
        
        # LSTM for temporal modeling
        x, _ = self.lstm(x)  # (B, T, hidden_dim*2)
        
        # Shared fully connected layer
        x = F.relu(self.fc_shared(x))  # (B, T, 512)
        x = self.dropout(x)
        
        # Task-specific output heads
        activations = torch.sigmoid(self.fc_activations(x))  # (B, T, F)
        onsets = torch.sigmoid(self.fc_onsets(x))  # (B, T, F)
        velocity = torch.sigmoid(self.fc_velocity(x))  # (B, T, F)
        
        # Transpose back to (B, F, T) format
        activations = activations.permute(0, 2, 1)
        onsets = onsets.permute(0, 2, 1)
        velocity = velocity.permute(0, 2, 1)

        return activations, onsets, velocity

