dataset:
  name: MAESTRO
  data_root: ./data/
  sample_rate: 16000
  segment_length_seconds: 10
  input_representation: cqt  # or mel, spectrogram
  n_bins: 88
  hop_length: 512
  normalize_audio: true
  add_noise: false

model:
  type: unet
  input_channels: 1
  output_channels: 88
  hidden_size: 128
  depth: 4
  dropout: 0.3
  use_batch_norm: true

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.0003
  optimizer: adam
  scheduler: cosine_annealing
  weight_decay: 1e-5
  grad_clip: 1.0
  loss_function: binary_crossentropy

evaluation:
  metrics: [f1, precision, recall, onset_offset_f1]
  threshold: 0.5
  use_mir_eval: true

logging:
  log_dir: outputs/
  checkpoint_dir: models/checkpoints/
  save_best_only: true
  save_every_n_epochs: 100

experiment:
  name: exp000_cqt_transformer
  seed: 42
  device: cuda
  num_workers: 4
  debug: false
  use_wandb: false

inference:
  threshold: 0.5
  apply_smoothing: true
  smoothing_window_size: 3
  output_format: midi

