defaults:
  - dataset: default
  - model: default
  - training: default
  - _self_

verbose: False 
experiment:
  name: base_experiment
  seed: 42
  device: cuda
  num_workers: 4 
  debug: true 
  use_wandb: true

evaluation:
  tolerance: .05 # how innacurate my onset predictions can be, in millis. Used when calculating metrics only

hydra:
  run:
    dir: .
